### ISSUE TITLE
Remove evil dependency

### ISSUE THREAD

**Issue by cute-jumper** [wbolster/evil-swap-keys#3]
Hi,

This is a very interesting package. However, it looks weird to me that this package needs to depend on evil because non-evil users may also want the functionalities provided by this package.

I just glanced over the code and I'm thinking about whether you can distinguish between evil and non-evil environment (using something like `boundp` or `fboundp`) and handle them respectively so that we can remove evil dependency from this package and make it more general. Would it be a huge amount of work to make it work without evil?

Thanks!

**Comment by wbolster** [comment]
thanks. 

there's also `number-lock` which is a bit simpler and has no evil dependencies. relevant discussions about how it relates to this package:
- https://github.com/melpa/melpa/pull/4180
- https://github.com/Liu233w/number-lock.el/issues/1

**Comment by cute-jumper** [comment]
Using minor mode is a better approach compared to changing the input method (`number-lock.el`).  Dealing with `evil` is more complicated. So if we can have a package that support both evil and non-evil environments, it should require less work starting from `evil-swap-keys.el`'s side. IIUC, this package seems more comprehensive than `number-lock.el`. I believe it would be better if these two packages can be merged into one.

What do you think?

**Comment by wbolster** [comment]
perhaps it's not that hard to make it work without evil as well. the main reason i started this package is that other alternatives were not evil-aware, and making them aware would've been non-trivial.

there are a few places that inspect evil state, but perhaps that can be wrapped in a conditional construct without complicating the code.

i'll have a look later.

**Comment by wbolster** [comment]
hey @cute-jumper, any chance you can give #4 a try? installing the package from melpa and then replacing the `.el` file with the one from that pull request branch should be enough to test it.

(caveat: i did not test it myself since i cannot use emacs without evil mode enabled... ;))

**Comment by cute-jumper** [comment]
Thanks. I found no problem using this without evil. I have a question, though: can we avoid setting the variable `evil-swap-keys-evil-aware`. Instead, using something like `(bound-and-true-p evil-mode)` to detect whether `evil` is enabled or not?

**Comment by wbolster** [comment]
yes, good idea. thanks for giving it a try. any other changes that you think would be a good idea?

**Comment by wbolster** [comment]
i pushed a new version to the branch for pr #4 to get rid of the "evil aware" defcustom. @cute-jumper, any chance you can give this updated version a try? (it seems to work fine when evil, which i use myself, is enabled.)

**Comment by cute-jumper** [comment]
Great! Works fine without evil. Maybe you can also update the package name on Melpa to reflect this change for better advertising?

**Comment by wbolster** [comment]
ok, thanks for testing.

handling package name changes and deprecating packages and so on on melpa sounds complicated though... and it would also change the prefix used for all public api in this package... :disappointed:

**Comment by cute-jumper** [comment]
That's right. Changing the name could be pretty tedious... Just a suggestion, anyway. I really appreciate your work!

**Comment by wbolster** [comment]
(reopened since not merged to master, need to update docs a bit and merge #4 first.)

**Comment by wbolster** [comment]
ok i merged #4 and updated the readme to clarify the new situation.

the updated version will appear on melpa soonish.

thanks for testing!
